apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: nfd-worker
rules:
- apiGroups:
  - nfd.openshift.io
  resources:
  - nodefeatures
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nfd-worker
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - policy
  resourceNames:
  - nfd-worker
  resources:
  - podsecuritypolicies
  verbs:
  - use
